# Generated by Django 5.0.4 on 2024-05-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ident',
            new_name='first',
        ),
    ]
