# Generated by Django 5.0.4 on 2024-04-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=255)),
                ('owner', models.TextField()),
                ('type', models.CharField(blank=True, max_length=266, null=True)),
                ('num_compte', models.PositiveIntegerField(null=True)),
                ('solde', models.FloatField(null=True)),
                ('etat', models.CharField(blank=True, max_length=266, null=True)),
                ('date_debut', models.DateField()),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
