# Generated by Django 5.0.4 on 2024-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=255)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('num_tel', models.PositiveIntegerField(null=True)),
                ('genre', models.TextField(blank=True, max_length=266, null=True)),
                ('depart', models.TextField(blank=True, max_length=266, null=True)),
                ('salaire', models.FloatField(null=True)),
                ('date_naissance', models.DateField()),
                ('date_recrut', models.DateField()),
            ],
            options={
                'ordering': ['-date_recrut'],
            },
        ),
    ]
